// File generated by FlutterFire CLI / Firebase setup for Blee.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVY-S12U5E7ORcWqd07WDwjLkMgrFjE4',
    appId: '1:351140845937:web:76c75d05357009e53abed0',
    messagingSenderId: '351140845937',
    projectId: 'dev-pacehive-4f465',
    authDomain: 'dev-pacehive-4f465.firebaseapp.com',
    storageBucket: 'dev-pacehive-4f465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqsuHfR1fHWHUSm8-Kf8dZoX2Zp9O5eI',
    appId: '1:351140845937:android:30dc81af3c91f7a23abed0',
    messagingSenderId: '351140845937',
    projectId: 'dev-pacehive-4f465',
    storageBucket: 'dev-pacehive-4f465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoHt2ficouUEPbpjeD4EN2EGhLiw92uyE',
    appId: '1:351140845937:ios:7faca002e11706b23abed0',
    messagingSenderId: '351140845937',
    projectId: 'dev-pacehive-4f465',
    storageBucket: 'dev-pacehive-4f465.appspot.com',
    iosBundleId: 'com.blee.blee',
  );
}
